#!/usr/bin/env bash
# Start ACL's backing services (MariaDB, Redis, Mailpit) and wait until each
# actually accepts connections. When its credentials secret is present, also
# publish the app to the internet through a Cloudflare Tunnel (ADR-0009).
#
# Runs on EVERY container start (postStartCommand), not only on create, so the
# services are up whenever you attach -- including after a codespace has been
# stopped and resumed, when the daemons are gone but their on-disk config is
# not. Safe to run by hand at any time:
#
#     bash .devcontainer/start-services.sh
#
# Idempotent: a service already answering is left alone. Redis and Mailpit run
# as the container user from ACL-owned files under ~/.acl -- no sudo, no distro
# service, nothing for a permission error to trip over.
set -uo pipefail

# shellcheck source=./config.sh
source "$(dirname "${BASH_SOURCE[0]}")/config.sh"

say()  { printf '\033[36m[ACL]\033[0m %s\n' "$1"; }
warn() { printf '\033[33m[ACL] %s\033[0m\n' "$1"; }

ACL_STATE_DIR="${HOME}/.acl"
mkdir -p "$ACL_STATE_DIR"

# --- MariaDB --------------------------------------------------------------
# `mysqladmin ping` succeeds only once the server is answering on the socket:
# `service start` returns as soon as the init script has forked, several
# seconds before the server is ready, and the next call would otherwise race it.
db_ready() {
  mysqladmin --protocol=socket ping >/dev/null 2>&1 \
    || mysqladmin -h "$ACL_DB_HOST" -P "$ACL_DB_PORT" --protocol=tcp ping >/dev/null 2>&1
}

ensure_mariadb() {
  if db_ready; then say "MariaDB already running."; return 0; fi
  if ! command -v mariadbd >/dev/null 2>&1 && ! command -v mysqld >/dev/null 2>&1; then
    warn "MariaDB is not installed. Run: bash .devcontainer/install-services.sh"; return 1
  fi
  say "Starting MariaDB..."
  # Codespaces containers have no systemd, so `service` runs the SysV init
  # script directly; fall back to launching the daemon ourselves.
  sudo service mariadb start >/dev/null 2>&1 \
    || sudo service mysql start >/dev/null 2>&1 \
    || sudo -b mariadbd-safe --skip-syslog >/dev/null 2>&1 \
    || true
  say "Waiting for MariaDB to accept connections..."
  for _ in $(seq 1 60); do
    if db_ready; then say "MariaDB is up."; return 0; fi
    sleep 1
  done
  sudo tail -n 30 /var/log/mysql/error.log 2>/dev/null || true
  warn "MariaDB did not become ready within 60s (log tail above)."
  return 1
}

# --- Redis ----------------------------------------------------------------
redis_cli()   { redis-cli --no-auth-warning -h "$ACL_REDIS_HOST" -p "$ACL_REDIS_PORT" -a "$ACL_REDIS_PASSWORD" "$@"; }
redis_ready() { [ "$(redis_cli ping 2>/dev/null)" = "PONG" ]; }

ensure_redis() {
  command -v redis-server >/dev/null 2>&1 \
    || { warn "redis-server not installed; SESSION/CACHE/QUEUE=redis will fail. Run install-services.sh."; return 1; }
  if redis_ready; then say "Redis already running."; return 0; fi

  local conf="${ACL_STATE_DIR}/redis.conf" data="${ACL_STATE_DIR}/redis-data"
  mkdir -p "$data"
  # Rewritten every start from config.sh so the password and limits can never
  # drift from the single source of truth. save "" + appendonly no: this is a
  # cache/session store, not a system of record -- nothing here needs to
  # outlive a restart, and TiDB/MariaDB hold everything that does.
  cat > "$conf" <<REDISCONF
# Generated by .devcontainer/start-services.sh -- development container only.
bind ${ACL_REDIS_HOST} -::1
port ${ACL_REDIS_PORT}
requirepass ${ACL_REDIS_PASSWORD}
maxmemory ${ACL_REDIS_MAXMEMORY}
maxmemory-policy ${ACL_REDIS_MAXMEMORY_POLICY}
appendonly no
save ""
daemonize yes
dir ${data}
pidfile ${data}/redis.pid
logfile ${data}/redis.log
REDISCONF
  chmod 600 "$conf"

  say "Starting Redis..."
  redis-server "$conf"
  for _ in $(seq 1 30); do
    if redis_ready; then say "Redis is up (maxmemory ${ACL_REDIS_MAXMEMORY}, policy ${ACL_REDIS_MAXMEMORY_POLICY})."; return 0; fi
    sleep 1
  done
  tail -n 20 "${data}/redis.log" 2>/dev/null || true
  warn "Redis did not become ready within 30s (log tail above)."
  return 1
}

# --- Mailpit --------------------------------------------------------------
mailpit_ready() { curl -sf "http://127.0.0.1:${ACL_MAIL_UI_PORT}/api/v1/info" >/dev/null 2>&1; }

ensure_mailpit() {
  command -v mailpit >/dev/null 2>&1 \
    || { warn "mailpit not installed; dev mail capture unavailable. Run install-services.sh."; return 1; }
  if mailpit_ready; then say "Mailpit already running."; return 0; fi

  local auth="${ACL_STATE_DIR}/mailpit-smtp-auth"
  # AUTH LOGIN needs a bcrypt-hashed credential file. PHP is already present, so
  # it generates the hash -- no apache2-utils/htpasswd dependency just for this.
  if [ ! -s "$auth" ]; then
    local hash
    hash="$(php -r 'echo password_hash($argv[1], PASSWORD_BCRYPT);' "$ACL_MAIL_PASSWORD" 2>/dev/null)"
    printf '%s:%s\n' "$ACL_MAIL_USER" "$hash" > "$auth"
    chmod 600 "$auth"
  fi

  say "Starting Mailpit..."
  # SMTP on loopback -- only the app, from inside the container, sends mail. The
  # web inbox binds all interfaces so the forwarded port reaches it in a browser
  # (Codespaces mediates that access; the container is not itself internet-facing).
  nohup mailpit \
    --smtp "127.0.0.1:${ACL_MAIL_SMTP_PORT}" \
    --listen "0.0.0.0:${ACL_MAIL_UI_PORT}" \
    --smtp-auth-file "$auth" \
    --smtp-auth-allow-insecure \
    >>"${ACL_STATE_DIR}/mailpit.log" 2>&1 &
  disown 2>/dev/null || true
  for _ in $(seq 1 30); do
    if mailpit_ready; then say "Mailpit is up (SMTP :${ACL_MAIL_SMTP_PORT}, inbox :${ACL_MAIL_UI_PORT})."; return 0; fi
    sleep 1
  done
  tail -n 20 "${ACL_STATE_DIR}/mailpit.log" 2>/dev/null || true
  warn "Mailpit did not become ready within 30s (log tail above)."
  return 1
}

# --- Cloudflare Tunnel (ADR-0009) -----------------------------------------
# Publishes the local app at ACL_TUNNEL_HOSTNAME across codespace stop/resume
# and rebuild via a LOCALLY-MANAGED tunnel. Its credentials JSON is a SECRET,
# supplied base64 in CLOUDFLARE_TUNNEL_CREDENTIALS_B64 (a GitHub Codespaces
# secret -- never committed, never in .env); absent => the tunnel is skipped so
# a credential-less codespace still boots cleanly. cloudflared dials OUT to the
# Cloudflare edge and has no inbound listener, so readiness is its own /ready
# metric on loopback and the don't-start-twice guard is a pgrep, not a port
# check. Running by credentials-file + UUID needs neither cert.pem nor the
# Cloudflare dashboard at run time.
tunnel_ready() { curl -sf "http://127.0.0.1:${ACL_TUNNEL_METRICS_PORT}/ready" >/dev/null 2>&1; }

ensure_cloudflared() {
  [ -n "${CLOUDFLARE_TUNNEL_CREDENTIALS_B64:-}" ] \
    || { say "No CLOUDFLARE_TUNNEL_CREDENTIALS_B64 in the environment; skipping Cloudflare Tunnel."; return 0; }
  command -v cloudflared >/dev/null 2>&1 \
    || { warn "cloudflared not installed; tunnel unavailable. Run install-services.sh."; return 1; }

  local dir="${HOME}/.cloudflared" conf creds id file
  conf="${dir}/config.yml"
  mkdir -p "$dir"; chmod 700 "$dir"
  creds="$(printf '%s' "$CLOUDFLARE_TUNNEL_CREDENTIALS_B64" | base64 -d 2>/dev/null)" \
    || { warn "CLOUDFLARE_TUNNEL_CREDENTIALS_B64 is not valid base64; skipping tunnel."; return 1; }
  id="$(printf '%s' "$creds" | sed -n 's/.*"TunnelID": *"\([0-9a-fA-F-]\{36\}\)".*/\1/p')"
  [ -n "$id" ] || { warn "No TunnelID in the decoded credentials; skipping tunnel."; return 1; }
  file="${dir}/${id}.json"
  printf '%s' "$creds" > "$file"; chmod 600 "$file"
  # Rewritten every start so the ingress can never drift: this host -> the
  # loopback app, everything else 404. no-autoupdate: install-services.sh owns
  # the binary. credentials-file + tunnel UUID => no cert.pem, no dashboard.
  cat > "$conf" <<TUNNELCONF
# Generated by .devcontainer/start-services.sh -- development container only.
tunnel: ${id}
credentials-file: ${file}
no-autoupdate: true
metrics: 127.0.0.1:${ACL_TUNNEL_METRICS_PORT}
ingress:
  - hostname: ${ACL_TUNNEL_HOSTNAME}
    service: http://localhost:${ACL_APP_PORT}
  - service: http_status:404
TUNNELCONF
  chmod 600 "$conf"

  if pgrep -x cloudflared >/dev/null 2>&1; then say "Cloudflare Tunnel already running."; return 0; fi
  say "Starting Cloudflare Tunnel (${ACL_TUNNEL_HOSTNAME} -> :${ACL_APP_PORT})..."
  nohup cloudflared --config "$conf" tunnel run >>"${ACL_STATE_DIR}/cloudflared.log" 2>&1 &
  disown 2>/dev/null || true
  for _ in $(seq 1 30); do
    if tunnel_ready; then say "Cloudflare Tunnel is up (edge connections established)."; return 0; fi
    sleep 1
  done
  tail -n 20 "${ACL_STATE_DIR}/cloudflared.log" 2>/dev/null || true
  warn "Cloudflare Tunnel did not report ready within 30s (log tail above)."
  return 1
}

# --- Bring everything up --------------------------------------------------
# Each service is independent: a failure in one is reported but does not stop
# the others, so an attached container stays as usable as it can be. MariaDB is
# the one hard requirement -- the test suite and the fallback database need it --
# so only its failure becomes the script's exit code.
rc=0
ensure_mariadb || rc=1
ensure_redis   || true
ensure_mailpit || true
ensure_cloudflared || true
exit "$rc"
